# Run Rails & Webpack concurrently
# Example file from webpack-rails gem
rails: bundle exec rails server
webpack: cd ../../ && ./node_modules/.bin/webpack-dev-server --config ./config/webpack.config.js
